services:
  feedback-web:
    build:
      context: .
      dockerfile: docker/frontend.Dockerfile
    ports:
      - "127.0.0.1:8080:80"

  feedback-backend:
    build:
      context: .
      dockerfile: docker/backend.Dockerfile
    ports:
      - "127.0.0.1:8091:8091"
    networks:
      - shared-services
    environment:
      - PORT=8091
      - NODE_ENV=production
      - NEO4J_HOST=${NEO4J_HOST}
      - NEO4J_USER=${NEO4J_USER}
      - NEO4J_PASSWORD=${NEO4J_PASSWORD}
      - NEO4J_DATABASE=${NEO4J_DATABASE}
      - NEO4J_DISABLE_LOSSLESS_INTEGERS=true
      - NEO4J_USEBIGINT=false
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT:-6379}

networks:
  shared-services:
    external: true

name: feedback-app