# docker/edge.proxy.conf
server {
  listen 443 ssl;
  server_name _;

  ssl_certificate     /etc/nginx/cert/star_industropolisbatang_co_id.crt;
  ssl_certificate_key /etc/nginx/cert/industropolisbatang_co_id.key;

  large_client_header_buffers 4 256k;

  # Frontend (SPA)
  location / {
    proxy_pass http://risk-web:80;

    proxy_buffer_size   128k;
    proxy_buffers       4 256k;
    proxy_busy_buffers_size 256k;
    proxy_temp_file_write_size 256k;

    proxy_connect_timeout   120s;
    proxy_send_timeout      120s;
    proxy_read_timeout      120s;
    send_timeout            120s;

    # proxy_set_header Host $host;
    # proxy_set_header X-Real-IP $remote_addr;
  }

  # Backend (NestJS)
  # If Nest HAS a global "/api" prefix (default here) → preserve path:
  location /api/ {
    proxy_pass http://risk-backend:8091;
    # proxy_set_header Host $host;
    # proxy_set_header X-Real-IP $remote_addr;
  }
}
